services:
  database:
    image: postgres:15
    container_name: postgres-microsservice-1
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: mateus
      POSTGRES_PASSWORD: gringo
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
